### ISSUE TITLE
Can the SDK control version updates?

### ISSUE THREAD

**Issue by vectorialgradha** [DelightSolutions/bflight-feedback#1]
Hi.

After looking through the B-flight documentation I don't see any API to check for newer versions. Say I upload a new APK file and want to force all users to upgrade to the new version. I was expecting something like [iVersion for iOS](https://github.com/nicklockwood/iVersion) where I could check the B-flight servers or a custom file and do this. Is this feature available?

**Comment by tthbalazs** [comment]
Hi!

Currently there is no way of forcing the user to upgrade to the newest version in our SDK, the user can always choose not to update.

**Comment by vectorialgradha** [comment]
Ok, thanks.
